export const carouselCards = ref([
    {imgUrl: `/assets/img/img1.jpg`, 
        title:"Huge Title 1",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate ad exercitationem ex a maxime tenetur reiciendis nobis, laborum recusandae animi ullam quam, fugiat similique, consectetur asperiores iusto atque consequatur reprehenderit?",
    },
    {imgUrl: `/assets/img/1_ashleyrophotography-orangeyellowflowerbee.jpg`, 
        title:"Huge Title 2",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate ad exercitationem ex a maxime tenetur reiciendis nobis, laborum recusandae animi ullam quam, fugiat similique, consectetur asperiores iusto atque consequatur reprehenderit?",
    },
    {imgUrl: `/assets/img/1_ianrdjohnson_springintheadelaidehills.jpg`, 
        title:"Huge Title 3", 
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate ad exercitationem ex a maxime tenetur reiciendis nobis, laborum recusandae animi ullam quam, fugiat similique, consectetur asperiores iusto atque consequatur reprehenderit?", 
    },
    {imgUrl: `/assets/img/3_camronshahmirzadi_pfeiffer beach-bigsurca.jpg`, 
        title:"Huge Title 4",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate ad exercitationem ex a maxime tenetur reiciendis nobis, laborum recusandae animi ullam quam, fugiat similique, consectetur asperiores iusto atque consequatur reprehenderit?",
    },
    {imgUrl: `/assets/img/03_gettyimages-590452303_super_resized.jpg`, 
        title:"Huge Title 5",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate ad exercitationem ex a maxime tenetur reiciendis nobis, laborum recusandae animi ullam quam, fugiat similique, consectetur asperiores iusto atque consequatur reprehenderit?",
    },
    {imgUrl: `/assets/img/4_chungooitan-tasmaniaaustralia.jpg`, 
        title:"Huge Title 6",
        content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate ad exercitationem ex a maxime tenetur reiciendis nobis, laborum recusandae animi ullam quam, fugiat similique, consectetur asperiores iusto atque consequatur reprehenderit?",
    },
]);